version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: api_app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/app.db
      - ADMIN_PASSWORD=pinball
      - RAY_PASSWORD=raypass
    volumes:
      - sqlite_data:/app/data

  ray:
    build:
      context: .
      dockerfile: ray_app/Dockerfile
    depends_on:
      - app
    network_mode: "host"
    environment:
      - RAY_API_URL=http://127.0.0.1:8000
      - RAY_API_PASSWORD=raypass

volumes:
  sqlite_data:
