version: "3.8"

networks:
  default:
    external: true
    name: "traefik_default"

services:
  origin:
    image: ghcr.io/youruser/pinball-score-tracker:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      SECRET_KEY: 9829uhf087w4hiou4whsdd
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.origin.rule=Host(`origin.beta.doze.dev`)"
      - "traefik.http.services.origin.loadbalancer.server.port=8000"
      - "flame.type=application"
      - "flame.name=Origin Beta"
      - "flame.url=https://origin.beta.doze.dev"
      - "flame.icon=mdi:gamepad-variant"

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
