version: "3.8"

networks:
  default:
    external: true
    name: "traefik_default"

services:
  origin:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:8000"  # HTTP
      - "9001:8001"  # WebSocket
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: origin-db
      POSTGRES_DB: postgres
      SECRET_KEY: 9829uhf087w4hiou4whsdd
      # PEM encoded key for signing machine claim handshakes
      RSA_PRIVATE_KEY: |
        -----BEGIN PRIVATE KEY-----
        ...
        -----END PRIVATE KEY-----
      # Brevo API key enables email sending
      BREVO_API_KEY: your_brevo_api_key
      BREVO_SENDER_EMAIL: no-reply@example.com
      BREVO_SENDER_NAME: Origin
    depends_on:
      - origin-db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.origin.rule=Host(`origin.beta.doze.dev`)"
      - "traefik.http.services.origin.loadbalancer.server.port=8000"
      - "flame.type=application"
      - "flame.name=Origin Beta"
      - "flame.url=https://origin.beta.doze.dev"
      - "flame.icon=mdi:gamepad-variant"

  origin-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


