name: Publish Beta

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Load workflow variables
        run: cat .github/workflows/vars.env >> $GITHUB_ENV
      - name: Load version
        run: echo "VERSION=$(python -c 'from app.version import __version__; print(__version__)')" >> $GITHUB_ENV
      - name: Build and push
        uses: ./.github/actions/docker-build
        with:
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-beta
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger Portainer deployment
        uses: ./.github/actions/portainer-deploy
        with:
          webhook: ${{ secrets.PORTAINER_WEBHOOK_BETA }}
