name: CI

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Load workflow variables
        run: cat .github/workflows/vars.env >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      - name: Load version
        if: github.event_name == 'push'
        run: echo "VERSION=$(python -c 'from app.version import __version__; print(__version__)')" >> $GITHUB_ENV
      - name: Push beta image
        if: github.event_name == 'push'
        uses: ./.github/actions/docker-build
        with:
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-beta
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:beta
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger Portainer beta deployment
        if: github.event_name == 'push'
        uses: ./.github/actions/portainer-deploy
        with:
          webhook: ${{ secrets.PORTAINER_WEBHOOK_BETA }}
      - name: Push release image
        if: github.event_name == 'release'
        uses: ./.github/actions/docker-build
        with:
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger Portainer release deployment
        if: github.event_name == 'release'
        uses: ./.github/actions/portainer-deploy
        with:
          webhook: ${{ secrets.PORTAINER_WEBHOOK_RELEASE }}
