name: Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Load workflow variables
        run: cat .github/workflows/vars.env >> $GITHUB_ENV
      - name: Build and push
        uses: ./.github/actions/docker-build
        with:
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger Portainer deployment
        uses: ./.github/actions/portainer-deploy
        with:
          webhook: ${{ secrets.PORTAINER_WEBHOOK_RELEASE }}
